### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by aminya** [sindresorhus/ora#162]
This error happens because Ora uses Mute-Stream which uses Legacy Streams which does not respect maxListeneters.

This is an issue that happens in Parcel cli that uses Ora: https://github.com/parcel-bundler/parcel/issues/4628
```js

(node:3812) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 33 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:451:17)
    at WriteStream.prependListener (node:events:474:14)
    at prependListener (node:internal/streams/legacy:100:20)
    at MuteStream.Stream.pipe (node:internal/streams/legacy:67:3)
    at MuteStream.pipe (C:\parcel\node_modules\mute-stream\mute.js:89:32)
    at new StdinDiscarder (C:\parcel\node_modules\ora\index.js:22:20)
    at Object.<anonymous> (C:\parcel\node_modules\ora\index.js:95:24)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/render.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/bundleReport.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/CLIReporter.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\test\/CLIReporter.test.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at C:\parcel\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\parcel\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (C:\parcel\node_modules\mocha\lib\mocha.js:809:10)
    at Object.exports.singleRun (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler (C:\parcel\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand (C:\parcel\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\parcel\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (C:\parcel\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\parcel\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\parcel\node_modules\mocha\lib\cli\cli.js:73:11)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
(node:3812) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 33 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:451:17)
    at WriteStream.addListener (node:events:467:10)
    at WriteStream.Readable.on (node:internal/streams/readable:870:35)
    at MuteStream.Stream.pipe (node:internal/streams/legacy:89:8)
    at MuteStream.pipe (C:\parcel\node_modules\mute-stream\mute.js:89:32)
    at new StdinDiscarder (C:\parcel\node_modules\ora\index.js:22:20)
    at Object.<anonymous> (C:\parcel\node_modules\ora\index.js:95:24)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/render.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/bundleReport.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/CLIReporter.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\test\/CLIReporter.test.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at C:\parcel\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\parcel\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (C:\parcel\node_modules\mocha\lib\mocha.js:809:10)
    at Object.exports.singleRun (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler (C:\parcel\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand (C:\parcel\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\parcel\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (C:\parcel\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\parcel\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\parcel\node_modules\mocha\lib\cli\cli.js:73:11)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by aminya** [comment]
Using bl (#163) changes the error. This may mean that this is not related to ora.

```


(node:25552) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 33 unpipe listeners added to [WriteStream]. Use emitter.setMaxList
eners() to increase limit
    at _addListener (node:events:451:17)
    at WriteStream.addListener (node:events:467:10)
    at WriteStream.Readable.on (node:internal/streams/readable:870:35)
    at BufferListStream.Readable.pipe (C:\parcel\node_modules\bl\node_modules\readable-stream\lib\_stream_readab
le.js:631:8)
    at new StdinDiscarder (C:\parcel\node_modules\ora\index.js:22:20)
    at new Ora (C:\parcel\node_modules\ora\index.js:99:21)
    at oraFactory (C:\parcel\node_modules\ora\index.js:383:9)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/render.js:33:15)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/bundleReport.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/CLIReporter.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\test\/CLIReporter.test.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at C:\parcel\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\parcel\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (C:\parcel\node_modules\mocha\lib\mocha.js:809:10)
    at Object.exports.singleRun (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler (C:\parcel\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand (C:\parcel\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\parcel\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (C:\parcel\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\parcel\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\parcel\node_modules\mocha\lib\cli\cli.js:73:11)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
(node:25552) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 33 error listeners added to [WriteStream]. Use emitter.setMaxListe
ners() to increase limit
    at _addListener (node:events:451:17)
    at WriteStream.prependListener (node:events:474:14)
    at prependListener (C:\parcel\node_modules\bl\node_modules\readable-stream\lib\_stream_readable.js:98:69)
    at BufferListStream.Readable.pipe (C:\parcel\node_modules\bl\node_modules\readable-stream\lib\_stream_readab
le.js:708:3)
    at new StdinDiscarder (C:\parcel\node_modules\ora\index.js:22:20)
    at new Ora (C:\parcel\node_modules\ora\index.js:99:21)
    at oraFactory (C:\parcel\node_modules\ora\index.js:383:9)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/render.js:33:15)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/bundleReport.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/CLIReporter.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\test\/CLIReporter.test.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at C:\parcel\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\parcel\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (C:\parcel\node_modules\mocha\lib\mocha.js:809:10)
    at Object.exports.singleRun (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler (C:\parcel\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand (C:\parcel\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\parcel\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (C:\parcel\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\parcel\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\parcel\node_modules\mocha\lib\cli\cli.js:73:11)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
(node:25552) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 33 close listeners added to [WriteStream]. Use emitter.setMaxListe
ners() to increase limit
    at _addListener (node:events:451:17)
    at WriteStream.addListener (node:events:467:10)
    at WriteStream.Readable.on (node:internal/streams/readable:870:35)
    at WriteStream.once (node:events:498:8)
    at BufferListStream.Readable.pipe (C:\parcel\node_modules\bl\node_modules\readable-stream\lib\_stream_readab
le.js:715:8)
    at new StdinDiscarder (C:\parcel\node_modules\ora\index.js:22:20)
    at new Ora (C:\parcel\node_modules\ora\index.js:99:21)
    at oraFactory (C:\parcel\node_modules\ora\index.js:383:9)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/render.js:33:15)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/bundleReport.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/CLIReporter.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\test\/CLIReporter.test.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at C:\parcel\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\parcel\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (C:\parcel\node_modules\mocha\lib\mocha.js:809:10)
    at Object.exports.singleRun (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler (C:\parcel\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand (C:\parcel\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\parcel\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (C:\parcel\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\parcel\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\parcel\node_modules\mocha\lib\cli\cli.js:73:11)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
(node:25552) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 33 finish listeners added to [WriteStream]. Use emitter.setMaxList
eners() to increase limit
    at _addListener (node:events:451:17)
    at WriteStream.addListener (node:events:467:10)
    at WriteStream.Readable.on (node:internal/streams/readable:870:35)
    at WriteStream.once (node:events:498:8)
    at BufferListStream.Readable.pipe (C:\parcel\node_modules\bl\node_modules\readable-stream\lib\_stream_readab
le.js:723:8)
    at new StdinDiscarder (C:\parcel\node_modules\ora\index.js:22:20)
    at new Ora (C:\parcel\node_modules\ora\index.js:99:21)
    at oraFactory (C:\parcel\node_modules\ora\index.js:383:9)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/render.js:33:15)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/bundleReport.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\src\/CLIReporter.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\parcel\packages\reporters\cli\test\/CLIReporter.test.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._compile (C:\parcel\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.newLoader [as .js] (C:\parcel\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at C:\parcel\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\parcel\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (C:\parcel\node_modules\mocha\lib\mocha.js:809:10)
    at Object.exports.singleRun (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha (C:\parcel\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler (C:\parcel\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand (C:\parcel\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\parcel\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (C:\parcel\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\parcel\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\parcel\node_modules\mocha\lib\cli\cli.js:73:11)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by klemenoslaj** [comment]
I am using `ora` when extending Angular Builders and it appears like the issue is with `ora`. I still need to dig a bit deeper to reason about it, but a very simple code elimination test points to `ora`.

I basically removed all the functionality but `ora` spinner, which I `.succeed()` right away, and get the errors already.

---

Another observation I made is that this only happens for me when I dynamically import a module. If I create a spinner outside and pass it into the function of the lazy module, everthing appears to be fine.

**Comment by marcins** [comment]
The issue as far as I understand is that Ora pipes into `process.stdout` - this is now done in the `stdin-discarder` package here: https://github.com/sindresorhus/stdin-discarder/blob/main/index.js#L14

When a Node Worker is created, by default it's `stdout` is piped into `process.stdout`, if you create more than 10 workers Node won't trigger the `MaxListenersExceededWarning`, and indeed calling `process.stdout.getMaxListeners()` will still return 10, however trying to pipe something into `process.stdout` at this point will trigger the warning.

I don't think there's a reliable way to fix this in `stdin-discarder` due to the limitation of not knowing how many things are already piped into `process.stdout`, however I have raised a PR to workaround this in Parcel at least by ensuring the `maxListener` value is at least equal to the number of Parcel workers + 1.
