### ISSUE TITLE
Can't be use with ES Modules

### ISSUE THREAD

**Issue by gihanrangana** [sindresorhus/ora#239]
getting an error when I try to run the ora on my ts project

```
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Projects\apix-js\@apixjs\api\node_modules\.pnpm\ora@8.0.1\node_modules\ora\index.js from C:\Projects\apix-js\@apixjs\api\lib\plugins\ora.ts not supported.
Instead change the require of index.js in C:\Projects\apix-js\@apixjs\api\lib\plugins\ora.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (C:\Projects\apix-js\@apixjs\api\node_modules\.pnpm\ts-node@10.9.2_@types+node@20.14.2_typescript@5.4.5\node_modules\ts-node\dist\index.js:851:20)
    at C:\Projects\apix-js\@apixjs\api\lib\plugins\ora.ts:35:65
    at async initPlugin (C:\Projects\apix-js\@apixjs\api\lib\plugins\ora.ts:35:17) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by sindresorhus** [comment]
Your project needs to be proper ESM: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by damusix** [comment]
Great package, but the fact that the maintainers have to be soooo edgy they refuse to support CJS is a huge bummer.

I'm using Node 22 with experimental ESM requires and it's still a PITA to get this running. What a shame. Wish y'all had a different mindset. It's really not that hard to add SWC and transpile into CJS.

**Comment by lrtoenjes** [comment]
@damusix I am attempting the same thing that you described. Care to elaborate on how you successfully configured things to get Ora to run in your CJS code using Node 22 and `--experimental-require-module` enabled?

**Comment by damusix** [comment]
@lrtoenjes I simply didn't use this package. If you really want to use it though, you can fork it and add the EJS to CJS compilations yourself. You should be able to reference it via git, or publish your own. LMK if you do so I use yours and not this one.

**Comment by lrtoenjes** [comment]
@damusix I was able to get the package working (without a fork) using `--experimental-require-module`. I had to make one tiny change because of how Node v22 _returns the name space object [directly](https://nodejs.org/en/blog/announcements/v22-release-announce?ref=blog.arcjet.com#support-requireing-synchronous-esm-graphs)_. That tiny change was:

`const spinner = ora.default('loading...');`

 where `default` is equivalent to the `ora` function that is loaded when doing the `require()` for older CJS versions of `ora`
